//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA.Models.Roles
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_User
    {
        public int ID { get; set; }
        public string LUser { get; set; }
        public string Pass { get; set; }
        public Nullable<int> TypePersonID { get; set; }
        public Nullable<int> U_E_ID { get; set; }
    
        public virtual T_TCliente T_TCliente { get; set; }
    }
}
