//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA.Models.Roles
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGINAS
    {


        public int SEQUENCIA { get; set; }
        public int IDPAGINA { get; set; }
        public string NOMBRE { get; set; }
        public string P_CONTROLLER { get; set; }
        public string P_ACTION { get; set; }
       
    }
}
