//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA.Models.Roles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PruebaDataContext : DbContext
    {
        public PruebaDataContext()
            : base("name=PruebaDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ROLES>().ToTable("ROLES");
        }
    
        public virtual DbSet<L_User> L_User { get; set; }
        public virtual DbSet<PAGINAS> Pagina { get; set; }
        public virtual DbSet<ROLES> Rol { get; set; }
        public virtual DbSet<ROLPAGINAS> RolPagina { get; set; }
        public virtual DbSet<T_TCliente> T_TCliente { get; set; }    }
}
