//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA.Models.Roles
{
    using System;
    using System.Collections.Generic;

    public partial class ROLES
    {


        public int R_ID { get; set; }
        public string R_NAME { get; set; }
        public string R_DESC { get; set; }

        public int R_H { get; set; }

}
}
