//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA.Models.Roles
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLPAGINAS
    {
        public int RP_ID { get; set; }
        public Nullable<int> RP_R_ID { get; set; }
        public Nullable<int> RP_P_ID { get; set; }
        public Nullable<int> RP_H { get; set; }
    
    }
}
